#!/usr/bin/env bash
# Install job-scan: pin an interpreter, link the skill, create the private
# workspace, arm the hook. Safe to re-run — it never overwrites config or .env.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE="${JOB_SCAN_WORKSPACE:-$HOME/.job-scan}"
SKILLS="$HOME/.claude/skills"

say()  { printf '\033[32m✓\033[0m %s\n' "$1"; }
warn() { printf '\033[33m!\033[0m %s\n' "$1"; }
die()  { printf '\033[31m✗\033[0m %s\n' "$1"; exit 1; }

# 1. Find a Python 3.14+ interpreter. `python3` is usually the system build,
#    which on macOS is still 3.9, so probe explicitly rather than assuming —
#    then pin the result so the skill, the scheduled task and manual runs all
#    agree on one interpreter.
REQ="3.14"
usable() { "$1" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3,14) else 1)' >/dev/null 2>&1; }

PY=""
if [ -n "${JOB_SCAN_PYTHON:-}" ]; then     # explicit override wins
  usable "$JOB_SCAN_PYTHON" \
    || die "JOB_SCAN_PYTHON=$JOB_SCAN_PYTHON is not Python $REQ+"
  PY="$JOB_SCAN_PYTHON"
fi
if [ -z "$PY" ]; then
  for cand in python3.16 python3.15 python3.14 python3; do
    path="$(command -v "$cand" 2>/dev/null)" || continue
    if usable "$path"; then PY="$path"; break; fi
  done
fi
if [ -z "$PY" ]; then          # pyenv builds whose shims aren't active globally
  for path in "$HOME"/.pyenv/versions/*/bin/python3.*; do
    [ -x "$path" ] || continue
    if usable "$path"; then PY="$path"; break; fi
  done
fi
[ -n "$PY" ] || die "no Python $REQ+ found — job-scan supports $REQ and newer only.
  Install one, then re-run:
    brew install python@3.14
    pyenv install 3.14.4     # if you use pyenv"

# A pyenv shim resolves per-directory (via .python-version) and dispatches on
# argv[0]. Pinning one would work here and then fail the moment the skill runs
# from another directory. Ask the interpreter where it actually lives.
REAL="$("$PY" -c 'import sys; print(sys.executable)' 2>/dev/null || true)"
if [ -n "$REAL" ] && [ -x "$REAL" ] && usable "$REAL"; then PY="$REAL"; fi
case "$PY" in
  */shims/*) die "resolved to a pyenv shim ($PY), which is directory-dependent.
  Pass an explicit interpreter instead:
    JOB_SCAN_PYTHON=\$HOME/.pyenv/versions/3.14.4/bin/python3.14 ./install.sh" ;;
esac

# No profile/ here. It is only the fallback resume.lib when that key is unset,
# and creating it empty made resume_text.py report "no_variants — check your
# variants globs" when the real problem is that resume.lib points nowhere.
# Leaving it absent produces "lib_not_found" instead, which names the fix.
mkdir -p "$WORKSPACE"/{data/raw,reports,cache,bin}

# 2. Build a virtualenv on top of it. The tool has no runtime dependencies, so
#    this is not about resolving any — it is about where an *optional* one would
#    land. Without a venv, `pip install pypdf` for a PDF resume library goes into
#    the base interpreter's global site-packages, which on a pyenv build is
#    shared by every project using that version.
VENV="$WORKSPACE/venv"
VENV_PY="$VENV/bin/python"
venv_base() { "$VENV_PY" -c 'import sys; print(sys.base_prefix)' 2>/dev/null; }
WANT_BASE="$("$PY" -c 'import sys; print(sys.base_prefix)')"

if [ ! -x "$VENV_PY" ]; then
  "$PY" -m venv "$VENV"
  say "virtualenv created at $VENV"
elif [ "$(venv_base)" != "$WANT_BASE" ]; then
  rm -rf "$VENV"
  "$PY" -m venv "$VENV"
  say "virtualenv rebuilt — its base interpreter had changed"
else
  warn "virtualenv already present, reused"
fi

# A symlink here does NOT work. CPython locates pyvenv.cfg relative to the
# executable path it was invoked with, and does not resolve the symlink first —
# so bin/python -> venv/bin/python makes it look for $WORKSPACE/pyvenv.cfg,
# find nothing, and silently run as the base interpreter with the venv inert.
# A wrapper that execs the real path gets genuine venv semantics.
rm -f "$WORKSPACE/bin/python"
cat > "$WORKSPACE/bin/python" <<WRAPPER
#!/bin/sh
# Generated by install.sh — exec, not a symlink, so pyvenv.cfg is found.
exec "$VENV_PY" "\$@"
WRAPPER
chmod +x "$WORKSPACE/bin/python"

"$WORKSPACE/bin/python" -c 'import sys; raise SystemExit(0 if sys.prefix != sys.base_prefix else 1)' \
  || die "the pinned interpreter is not running inside the venv"
say "interpreter pinned: $("$WORKSPACE/bin/python" -V 2>&1)"
say "  venv   $VENV"
say "  base   $PY"

# 3. Config and credential templates — never overwritten.
say "workspace at $WORKSPACE"

if [ ! -f "$WORKSPACE/config.toml" ]; then
  cp "$REPO/config.example.toml" "$WORKSPACE/config.toml"
  say "config.toml created — edit the TODO fields"
else
  warn "config.toml already exists, left untouched"
fi

if [ ! -f "$WORKSPACE/.env" ]; then
  cp "$REPO/.env.example" "$WORKSPACE/.env"
  chmod 600 "$WORKSPACE/.env"
  say ".env created (mode 600) — add your IMAP app password"
else
  warn ".env already exists, left untouched"
fi

# 4. Make the skill visible to Claude Code from any directory.
mkdir -p "$SKILLS"
if [ -L "$SKILLS/job-scan" ]; then
  ln -sfn "$REPO" "$SKILLS/job-scan"
  say "skill symlink refreshed"
elif [ -e "$SKILLS/job-scan" ]; then
  warn "$SKILLS/job-scan exists and is not a symlink — leaving it alone"
else
  ln -s "$REPO" "$SKILLS/job-scan"
  say "skill linked into $SKILLS"
fi

# 5. Arm the pre-commit hook that keeps personal data out of a public repo.
if [ -d "$REPO/.git" ]; then
  chmod +x "$REPO/.githooks/pre-commit"
  git -C "$REPO" config core.hooksPath .githooks
  say "pre-commit hook armed"
else
  warn "not a git repo yet — run 'git init' then re-run to arm the hook"
fi

cat <<EOF

Next:
  1. Put your IMAP app password in $WORKSPACE/.env
     Gmail needs an App Password (2FA on): https://myaccount.google.com/apppasswords
  2. Point resume.lib in $WORKSPACE/config.toml at your resume repo,
     and fill in the TODO fields under [profile]
  3. Verify:
       $WORKSPACE/bin/python $REPO/scripts/fetch_mail.py --check
       $WORKSPACE/bin/python $REPO/scripts/resume_text.py --list
  4. In Claude Code, run the skill:  /job-scan
EOF
