import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { cleanText, dedupeKey, extractLinks, htmlToText, type Link } from "../src/lib/mail-text.js";

// Expected values were generated by scripts/mail_text.py, the reference implementation.
interface Fixtures {
  html_to_text: { name: string; html: string; expected: string }[];
  clean_text: { name: string; text: string; max_chars: number; expected: string }[];
  extract_links: { name: string; html: string; limit: number; expected: Link[] }[];
  dedupe_key: { url: string; expected: string }[];
}

const fx: Fixtures = JSON.parse(
  readFileSync(new URL("../../tests/fixtures/mail_text.json", import.meta.url), "utf8"),
);

describe("htmlToText matches mail_text.html_to_text", () => {
  it.each(fx.html_to_text.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(htmlToText(c.html)).toBe(c.expected);
  });
});

describe("cleanText matches mail_text.clean_text", () => {
  it.each(fx.clean_text.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(cleanText(c.text, c.max_chars)).toBe(c.expected);
  });
});

describe("extractLinks matches mail_text.extract_links", () => {
  it.each(fx.extract_links.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(extractLinks(c.html, c.limit)).toEqual(c.expected);
  });
});

describe("dedupeKey matches mail_text.dedupe_key", () => {
  it.each(fx.dedupe_key.map((c) => [c.url, c] as const))("%s", (_n, c) => {
    expect(dedupeKey(c.url)).toBe(c.expected);
  });
});
