import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { latexToText } from "../../src/lib/resume/latex.js";
import { normalizeResumeText } from "../../src/lib/resume/text.js";

// Expected values were generated by scripts/latex_text.py and the
// normalisation in scripts/resume_text.text_for, the reference implementations.
const fx: {
  latex_to_text: { name: string; tex: string; expected: string }[];
  normalize: { name: string; text: string; expected: string }[];
} = JSON.parse(
  readFileSync(new URL("../../../tests/fixtures/latex_text.json", import.meta.url), "utf8"),
);

describe("latexToText matches latex_text.latex_to_text", () => {
  it.each(fx.latex_to_text.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(latexToText(c.tex)).toBe(c.expected);
  });
});

describe("normalizeResumeText matches resume_text.text_for", () => {
  it.each(fx.normalize.map((c) => [c.name, c] as const))("%s", (_n, c) => {
    expect(normalizeResumeText(c.text)).toBe(c.expected);
  });
});
